Document: andi
Title: Debian andi Manual
Author: <insert document author here>
Abstract: This manual describes what andi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/andi/andi.sgml.gz

Format: postscript
Files: /usr/share/doc/andi/andi.ps.gz

Format: text
Files: /usr/share/doc/andi/andi.text.gz

Format: HTML
Index: /usr/share/doc/andi/html/index.html
Files: /usr/share/doc/andi/html/*.html
